---
- name: Converge
  hosts: all
  roles:
    - role: transitiv.yarn

  pre_tasks:
    - name: Install required packages on Debian
      apt:
        name:
          - apt-transport-https
          - gnupg
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Set nodesource_version to 11 on CentOS / RHEL 6
      set_fact:
        nodesource_version: 11
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version == '6'

  post_tasks:
    - name: Ensure yarn is installed
      stat:
        path: /usr/bin/yarn
      register: result
      changed_when: false
      failed_when: result.stat.islnk is not defined or not result.stat.islnk
